### ISSUE TITLE
There's no orange in the zip file

### ISSUE THREAD

**Issue by edjiang** [soggybag/Orange-Tree#1]
Please fix :)

**Comment by soggybag** [comment]
Fixed! Thanks for pointing that out.

**Comment by edjiang** [comment]
I still don't see the orange in the zip file.

**Comment by soggybag** [comment]
It should be there. It's in the zip locally but Github doesn't seem to be updating the zip in the repo online.

**Comment by edjiang** [comment]
Latest update works!
