### ISSUE TITLE
CloudsEmitter

### ISSUE THREAD

**Issue by edjiang** [soggybag/Orange-Tree#3]
You tell people to name the file `CloudsEmitter` but is later referenced with `SKEmitterNode(fileNamed: "CloudEmitter")`

**Comment by soggybag** [comment]
"CloudEmitter" is the name of the SpriteKit Particle file you created in the previous step. "SKEmitterNode" is the name of the class. You are creating a new instance of "SKEmitterNode" with the particle file you created and edited. If your Emitter.sks file was named something else you'd need to change the name: `SKEmitterNode(fileNamed: "NameOfFileHere")`
